### ISSUE TITLE
`maxFileCount` not working

### ISSUE THREAD

**Issue by huynguyen93** [upload-io/uploader#19]
I set maxFileCount = 2 but I can still upload more than 2 images

https://codepen.io/upload-js/pen/QWOZWZR?editors=1010

**Comment by ljwagerfield** [comment]
Hi @huynguyen93,

Thank you for raising!

The issue I believe you're experiencing is when you upload all the files as a single drop-and-drop batch, rather than one by one. In this case, the drop-and-drop batch size can be larger than the `maxFileCount`.

This has been resolved in **[this commit](https://github.com/upload-io/uploader/commit/f17a311de5ce5f4c5f407fc7e1b222c0bf43697d)** and has been released in **[1.47.0](https://github.com/upload-io/uploader/releases/tag/v1.47.0)**, a long with several other fixes:

- Cropper not initializing correctly for subsequent images.
- The "X of Y images" header above the cropper causes the image to shift down when it's displayed (i.e. after the 2nd+ image uploads, and you still have the cropper open on the 1st image).

Please let me know if this resolves your issue 😄

**Comment by huynguyen93** [comment]
No, I clicked button “Select files” to upload, not drag-and-drop.
But even so, I think he behavior should be: no files are uploaded at all,
and an error message is shown.

Vào Th 3, 16 thg 8, 2022 lúc 02:01 Lawrence Wagerfield <
***@***.***> đã viết:

**Comment by huynguyen93** [comment]
Also, when `maxFileCount`, the button label should be `Upload images`

**Comment by huynguyen93** [comment]
> Hi @huynguyen93,
> 
> Thank you for raising!
> 
> The issue I believe you're experiencing is when you upload all the files as a single drop-and-drop batch, rather than one by one. In this case, the drop-and-drop batch size can be larger than the `maxFileCount`.
> 
> This has been resolved in **[this commit](https://github.com/upload-io/uploader/commit/f17a311de5ce5f4c5f407fc7e1b222c0bf43697d)** and has been released in **[1.47.0](https://github.com/upload-io/uploader/releases/tag/v1.47.0)**, a long with several other fixes:
> 
> * Cropper not initializing correctly for subsequent images.
> * The "X of Y images" header above the cropper causes the image to shift down when it's displayed (i.e. after the 2nd+ image uploads, and you still have the cropper open on the 1st image).
> 
> Please let me know if this resolves your issue smile

Thanks, I've tested again, set `maxFileCount` = 2, then upload 3 images, only first 2 ones are uploaded -> better than before!

**Comment by ljwagerfield** [comment]
> Also, when maxFileCount > 1, the button label should be Upload images

From [1.48.0](https://github.com/upload-io/uploader/releases/tag/v1.48.0) we've started automatically setting `multi: true` if it's not explicitly specified _and_ `maxFileCount > 1`, which will have the effect you're mentioning. If it's specifically to do with the wording re. when `multi` is `enabled`, then that's more to do [with the locale](https://github.com/upload-io/uploader/blob/main/lib/src/modules/locales/EN_US.ts#L32) which you can override for yourself.

> Thanks, I've tested again, set maxFileCount = 2, then upload 3 images, only first 2 ones are uploaded -> better than before!

If you're happy with truncating, rather than denying the entire batch, then we'll close the issue 😄
