### ISSUE TITLE
Cropped uploads fail with disabled file name override

### ISSUE THREAD

**Issue by kincaidoneil** [upload-io/uploader#20]
https://github.com/upload-io/uploader/blob/8cb2dcc77210a357eea232c635347a6e39203b1f/lib/src/components/widgets/uploader/components/editors/ImageCropper.tsx#L81-L87

The Uploader appends `.crop` to the original filename when uploading a cropped image. However, when an API key has "File name can be overridden by the uploader" _disabled_, the upload fails because the edited file name cannot match the template.

**Comment by ljwagerfield** [comment]
You are correct: 

The Uploader component will fail on image cropping if the API key is configured with "File name overrides disabled". This is because the Uploader component is still beholden to the same security and permissions features of the Upload API as all other API users.

However, we do need to improve the developer experience here, either by noting this behaviour next to said checkbox in the Upload Dashboard, or even by finding a solution that prevents the error from occurring.

I would love to hear your suggestions on what you feel a good solution would be.

The simplest solution is to remove the `path` field on line 87. This would allow the Upload API to assign the crop file's path automatically, like it does for the main image.

The downside is that the crop file becomes less-obviously linked to the original image in the Upload Dashboard. 

Currently, you have this:

```
some-image-name.jpeg
some-image-name.jpeg.crop
```

Or even this (if the file name pattern configured for the API key uses unique digits):

```
Xf8aA0gpH.jpeg
Xf8aA0gpH.jpeg.crop
```

However, if we removed `path` on line 87, then the upload would always succeed, but you would end up with the following:

```
UYtK94Ed7.jpeg.crop
... potentially millions of files ...
Xf8aA0gpH.jpeg
```

WDYT?

**Comment by ljwagerfield** [comment]
> Yes, documenting this behavior there would be helpful 👍

<img width="695" alt="image" src="https://user-images.githubusercontent.com/3638917/228369043-cafe34b0-5ba1-45c0-92c0-9fdbf045ab02.png">

This has now been deployed, thank you for confirming it would be useful!

> Or also, better documenting how the built-in cropper works

This has now been added here:

https://github.com/upload-io/uploader#how-does-image-cropping-work

> maybe the API could ignore the client-provided filename instead of failing

Since it's a permissions failure, it's best to hard-fail the request, rather than automatically fallback onto alternative behaviour. 

I understand the suggestion, and that it would make for a nicer experience in this specific case, but in the wider context of security re. the Upload API, I don't think it would be wise to make this change. 

> In any case, better understanding this behavior resolves it for me!

Closing 👍 

LMK if you have any further questions!
